---

- name: Synchronize whole directories
  copy:
    src={{ item.value.src }}
    dest={{ item.value.dest }}
    owner={{ item.value.owner|default(configurator.default.fulldir.owner) }}
    group={{ item.value.group|default(configurator.default.fulldir.group) }}
    force={{ item.value.force|default(configurator.default.fulldir.force) }}
  with_dict: "{{ configurator.fulldirs }}"
  notify: "{{ item.value.notify|default(configurator.default.fulldir.notify) }}"
  tags:
    - configurator-fulldirs

- name: Create directories tree
  file:
    path={{ item.dir }}
    mode={{ item.mode|default(configurator.default.directory.mode) }}
    owner={{ item.owner|default(configurator.default.directory.owner) }}
    group={{ item.group|default(configurator.default.directory.group) }}
    state=directory
  with_items: "{{ configurator.directories }}"
  notify: "{{ item.notify|default(configurator.default.directory.notify) }}"
  tags:
    - configurator-directories

- name: Copy files
  copy:
    dest={{ item.file }}
    src={{ item.src }}
    mode={{ item.mode|default(configurator.default.file.mode) }}
    owner={{ item.owner|default(configurator.default.file.owner) }}
    group={{ item.group|default(configurator.default.file.group) }}
    force={{ item.force|default(configurator.default.file.force) }}
    backup={{ item.backup|default(configurator.default.file.backup) }}
  with_items: "{{ configurator.files }}"
  notify: "{{ item.notify|default(configurator.default.file.notify) }}"
  tags:
    - configurator-files

- name: Create symlinks with force mode
  file:
    dest={{ item.dest }}
    src={{ item.src }}
    force={{ item.force|default(configurator.default.symlink.force) }}
    state=link
  with_items: "{{ configurator.symlinks }}"
  when: "item.force"
  notify: "{{ item.notify|default(configurator.default.symlink.notify) }}"
  tags:
    - configurator-symlinks

- name: Create symlinks without force mode
  command: ln -s {{ item.src }} {{ item.dest }}
    creates={{ item.dest }}
    chdir={{ item.chdir|default('.') }}
  with_items: "{{ configurator.symlinks }}"
  when: "not item.force"
  notify: "{{ item.notify|default(configurator.default.symlink.notify) }}"
  tags:
    - configurator-symlinks
