---

- name: Delete individual files and directories (recursively)
  file:
    path={{ item.value }}
    state=absent
  with_dict: "{{ configurator.delete }}"
  tags:
    - configurator-delete
    - configurator-rsyncdirs
    - configurator-fulldirs
    - configurator-directories
    - configurator-files
    - configurator-templates
    - configurator-symlinks

# @todo make this not ask for password
# @see https://github.com/ansible/ansible/issues/23834
- name: Synchronize whole directories with rsync
  synchronize:
    src={{ item.value.src }}
    dest={{ item.value.dest }}
    archive={{ item.value.archive|default(configurator.default.rsyncdir.archive) }}
  with_dict: "{{ configurator.rsyncdirs }}"
  notify: "{{ item.value.notify|default(configurator.default.rsyncdir.notify) }}"
  tags:
    - configurator-rsyncdirs

- name: Synchronize whole directories
  copy:
    src={{ item.value.src }}
    dest={{ item.value.dest }}
    owner={{ item.value.owner|default(configurator.default.fulldir.owner) }}
    group={{ item.value.group|default(configurator.default.fulldir.group) }}
    force={{ item.value.force|default(configurator.default.fulldir.force) }}
  with_dict: "{{ configurator.fulldirs }}"
  notify: "{{ item.value.notify|default(configurator.default.fulldir.notify) }}"
  tags:
    - configurator-fulldirs

- name: Create/update directories tree
  file:
    path={{ item.key if not item.value or item.value.dir is not defined else item.value.dir }}
    mode={{ item.value.mode|default(configurator.default.directory.mode) }}
    owner={{ item.value.owner|default(configurator.default.directory.owner) }}
    group={{ item.value.group|default(configurator.default.directory.group) }}
    state={{ item.value.state|default(configurator.default.directory.state) }}
  with_dict: "{{ configurator.directories }}"
  when: item.value.state|default(configurator.default.directory.state) in configurator.default.directory.possible_states
  notify: "{{ item.notify|default(configurator.default.directory.notify) }}"
  tags:
    - configurator-directories

- name: Copy files
  copy:
    dest={{ item.file }}
    src={{ item.src }}
    mode={{ item.mode|default(configurator.default.file.mode) }}
    owner={{ item.owner|default(configurator.default.file.owner) }}
    group={{ item.group|default(configurator.default.file.group) }}
    force={{ item.force|default(configurator.default.file.force) }}
    backup={{ item.backup|default(configurator.default.file.backup) }}
  with_items: "{{ configurator.files }}"
  notify: "{{ item.notify|default(configurator.default.file.notify) }}"
  tags:
    - configurator-files

- name: Render & —Åopy templates
  template:
    dest: "{{ item.value.dest }}"
    src: "{{ item.value.src }}"
    mode: "{{ item.value.mode|default(configurator.default.template.mode) }}"
    owner: "{{ item.value.owner|default(configurator.default.template.owner) }}"
    group: "{{ item.value.group|default(configurator.default.template.group) }}"
    force: "{{ item.value.force|default(configurator.default.template.force) }}"
    backup: "{{ item.value.backup|default(configurator.default.template.backup) }}"
  with_dict: "{{ configurator.templates }}"
  notify: "{{ item.notify|default(configurator.default.template.notify) }}"
  tags:
    - configurator-templates

- name: Create symlinks with force mode
  file:
    dest={{ item.dest }}
    src={{ item.src }}
    force={{ item.force|default(configurator.default.symlink.force) }}
    state=link
  with_items: "{{ configurator.symlinks }}"
  when: "item.force"
  notify: "{{ item.notify|default(configurator.default.symlink.notify) }}"
  tags:
    - configurator-symlinks

- name: Create symlinks without force mode
  command: ln -s {{ item.src }} {{ item.dest }}
    creates={{ item.dest }}
    chdir={{ item.chdir|default('.') }}
  with_items: "{{ configurator.symlinks }}"
  when: "not item.force"
  notify: "{{ item.notify|default(configurator.default.symlink.notify) }}"
  tags:
    - configurator-symlinks
